community dynamics analysis demo app
oss-aspen/Rappel pull request #219
Opened 2023-07-05 19:04 UTC by mariashev

2023-07-05 20:05 UTC, JamesKunstle requested changes
I made some requests to pull apart some large functions. Since this is going to be a part of Rappel, let's organize this applet for maintainability (ultimately we'll need to integrate it into 8K so we need to be able to understand the code.

My major recommendation is to restructure the application into a few files, handling (1) data collection and ingestion, (2) graph rendering and annotation, (3) application page struction, (4) application behavior, e.g. callbacks. We can talk about how to do this together if you'd like.

2023-07-05 20:05 UTC, JamesKunstle commented on demo_apps/collab_network/app.py
> +        node_colors = ['r' if pagerank_scores[n] >= threshold_score else 'b' if n in prev_nodes else 'y' for n in snapshot_G.nodes()]
now you're also running the rendering process in a single function. this function (1) builds the graph object, (2) runs pagerank, and (3) renders the frames of the animation. 

should subdivide into like, 10 functions total.

2023-07-05 20:05 UTC, JamesKunstle commented on demo_apps/collab_network/app.py
> +        counts = Counter(node_colors)
what is this block of code doing?

2023-07-05 20:05 UTC, JamesKunstle commented on demo_apps/collab_network/app.py
> +def draw_network(slider_value, slider_marks, data, cmt_weight, ism_weight, pr_weight, prm_weight):
break apart function into graph building, pagerank, and rendering functions.

2023-07-13 18:22 UTC, cdolfi requested changes
First time really getting to dive into the code on your work and super excited about this. It took me until I finished reviewing everything hopping around to get a grasp on what is going on since it was my first go around. Most of my changes revolve around using datetime, dataframes, and some dash stuff. Before diving into this I would really recommend looking at: 
- https://github.com/oss-aspen/8Knot/blob/dev/pages/overview/visualizations/active_drifting_contributors.py 
- https://github.com/oss-aspen/8Knot/blob/dev/pages/overview/visualizations/issues_over_time.py 
and the logic used there. Please ping me with any questions going through that! Lets meet and talk through this a bit once you have time to digest this

2023-07-13 18:22 UTC, cdolfi commented on demo_apps/collab_network/dashboard/plots.py
> +    global total_frames, promo_list, demo_list, core, peripheral, new, all_time, avg_intervals
Why use global variables?

2023-07-13 18:22 UTC, cdolfi commented on demo_apps/collab_network/dashboard/plots.py
> +    promo_list = []
Using a pandas df probably will make this a lot easier. Will put more detail in my overall review comment

2023-07-13 18:22 UTC, cdolfi commented on demo_apps/collab_network/dashboard/plots.py
> +    core_trace, per_trace, new_trace, all_time_trace, promo_trace, demo_trace, avg_int_trace = plot_traces(intervals, core, peripheral, new, all_time, peripheral_to_core_list, core_to_peripheral_list
Lets talk about this a bit. I feel like plot traces and trends code would make more sense to be broken down by figure instead of trends and traces. Could see just putting it all into one function as well.  You can define fig1 = go.Figure() (and 2 and 3 at the beginning of a function and then using if statements for 1 and 2 to add traces onto the figure (figure 3 is always the same). Then use fig.update_layout.

see create_figure here: https://github.com/oss-aspen/8Knot/blob/dev/pages/overview/visualizations/issues_over_time.py

2023-07-17 15:11 UTC, mariashev commented on demo_apps/collab_network/dashboard/graph_helper.py
> +            else:
the else statement is to the 119 if: if an edge exists -> increase weight, if it doesn't -> create edge

2023-07-18 17:14 UTC, mariashev commented on demo_apps/collab_network/dashboard/network_graph.py
> +    new_value = [(slider_value[0] + 1) % (slider_max + 1), (slider_value[1] + 1) % (slider_max + 1)]
This callback updates the slider value during the animation

2023-07-25 20:36 UTC, JamesKunstle requested changes
Let's work on documentation this round. Before I do more in-depth review I'd like to have docstrings on functions and annotations on blocks of code so I know what you're doing in the process. I can read Python but w/o more foreknowledge of the data's structure it's pretty difficult to maintain code like this- plain english descriptions are necessary.

Overall though, we're now in the refinement phase. Excellent work.

2023-07-25 20:36 UTC, JamesKunstle commented on demo_apps/collab_network/dashboard/graph_helper.py
> +def build_graph(data, start_date, end_date, cmt_weight, ism_weight, pr_weight, prm_weight):
Let's break this up into smaller graph builder functions. That way we can build the subgraphs if we need to.

2023-07-25 20:36 UTC, JamesKunstle commented on demo_apps/collab_network/dashboard/graph_helper.py
> +def find_threshold(scores, threshold):
Write docstring

2023-07-25 20:36 UTC, JamesKunstle commented on demo_apps/collab_network/dashboard/graph_helper.py
> +    if threshold[0] == 'elbow':
Comment on the threshold options, annotate the meaning of the calculations below. e.g. "diff is ...", "knee_index is..."

This is so that we can maintain this code in the future.

2023-07-25 20:36 UTC, JamesKunstle commented on demo_apps/collab_network/dashboard/graph_helper.py
> +    scaled_scores = {node: (pagerank_scores[node] - min_score) / (max_score - min_score) for node in G.nodes()}
"normalized" rather than "scale" I think.

2023-07-25 20:36 UTC, JamesKunstle commented on demo_apps/collab_network/dashboard/graph_helper.py
> +def pagerank(G):
rename function "apply_pagerank" or something. 
add docstring.

2023-07-25 20:36 UTC, JamesKunstle commented on demo_apps/collab_network/dashboard/network_graph.py
> +def draw_network(G, start_date, end_date, pagerank_scores, scaled_scores, threshold_score):
docstring

2023-07-25 20:36 UTC, JamesKunstle commented on demo_apps/collab_network/dashboard/network_graph.py
> +def draw_traces(G, pos, node_colors):
docstring

2023-07-25 20:36 UTC, JamesKunstle commented on demo_apps/collab_network/dashboard/network_graph.py
> +network_graph_layout = html.Div(
++ agreed. If you can use CSS classes rather than inline styling that'd be very convenient.

2023-07-25 20:36 UTC, JamesKunstle commented on demo_apps/collab_network/dashboard/network_graph.py
> +def update_slider_value(n_intervals, slider_value, slider_max):
docstring

2023-07-25 20:36 UTC, JamesKunstle commented on demo_apps/collab_network/dashboard/network_graph.py
> +def toggle_animation(play_clicks, pause_clicks, interval_disabled, slider_value):
docstring

2023-07-25 20:36 UTC, JamesKunstle commented on demo_apps/collab_network/dashboard/network_graph.py
> +def update_network(n_clicks, n_intervals, repo_org, repo_name, slider_value, marks, cmt_weight, ism_weight, pr_weight, prm_weight, threshold_type, threshold_value):
docstring, annotate the lines of this function w.r.t their utility. This is pretty dense to read.

2023-07-25 20:36 UTC, JamesKunstle commented on demo_apps/collab_network/dashboard/plots.py
> +def get_plot_data(data, marks, cmt_weight, ism_weight, pr_weight, prm_weight, threshold):
docstring

2023-07-25 20:36 UTC, JamesKunstle commented on demo_apps/collab_network/dashboard/plots.py
> +def init_sets(G):
docstring

2023-07-25 20:36 UTC, JamesKunstle commented on demo_apps/collab_network/dashboard/plots.py
> +def plot_fig1(marks, df, card_checks):
docstring

2023-07-25 20:36 UTC, JamesKunstle commented on demo_apps/collab_network/dashboard/plots.py
> +def plot_fig2(marks, df, promo_checks):
docstring

2023-07-25 20:36 UTC, JamesKunstle commented on demo_apps/collab_network/dashboard/plots.py
> +def plot_fig3(marks, df):
docstring

2023-07-25 20:36 UTC, JamesKunstle commented on demo_apps/collab_network/dashboard/plots.py
> +def plot(n_clicks, repo_org, repo_name, marks, card_checks, promo_checks, cmt_weight, ism_weight, pr_weight, prm_weight, threshold_type, threshold_value):
docstring.

Should probably break this up into 3 callbacks, one for each figure.

2023-07-25 20:36 UTC, JamesKunstle commented on demo_apps/collab_network/dashboard/sidebar.py
> +def generate_slider_marks(interval, dates):
docstring

2023-07-25 20:36 UTC, JamesKunstle commented on demo_apps/collab_network/dashboard/sidebar.py
> +def update_threshold_input(value):
docstring

2023-07-25 20:36 UTC, JamesKunstle commented on demo_apps/collab_network/dashboard/wsgi.py
> +from .app import server as application
do you need this file?

2023-07-25 21:15 UTC, cdolfi commented on demo_apps/collab_network/dashboard/plots.py
> +def plot(n_clicks, repo_org, repo_name, marks, card_checks, promo_checks, cmt_weight, ism_weight, pr_weight, prm_weight, threshold_type, threshold_value):
^ good call. In that case I think each of the functions can just be a part of the call back

2023-07-25 21:17 UTC, cdolfi commented
@mariashev Ill do my next round of in depth review once the comments and doc strings are in as well. Great job with this though, thats a major refactor and huge fan of how it looks now with datetime and dfs

2023-08-03 15:48 UTC, JamesKunstle requested changes
Could of organizational requests.
Would also like to have a README that describes the applet, what it does, and what the subcomponents are meant to do (the file structure, for instance). 

For instance, describing what the Elbow does is critical to the user and developer experience.

Documenting this application, and any assumptions or 'gotchas' you encountered, is critical to its sustainability and usefulness going forward.

2023-08-03 15:48 UTC, JamesKunstle commented on demo_apps/community_dynamics_analysis/components/network_graph/network_graph.py
> +    return edge_trace, node_trace
I think these graphing helper functions should be in graph_utils because they're specific to the networks being created. They should be reusable later.

2023-08-03 15:48 UTC, JamesKunstle commented on demo_apps/community_dynamics_analysis/components/network_graph/network_graph_callbacks.py
> +    data = fetch_data(repo_org, repo_name, ['cmt', 'ism', 'pr', 'prm']) # fetch data from Augur
So, each time a new graph should be rendered, the data is re-queried? For this applet I think this is fine but if this is extended we'd want to cache the data on the first render and just grab it from cache on re-render.

2023-08-03 17:19 UTC, JamesKunstle commented on demo_apps/community_dynamics_analysis/graph_utils/graph_helper.py
> +        elbow_index = np.argmax(diff) + 1
nvm, you're right

2023-08-04 20:29 UTC, closed without merging