Repo discovery
oss-aspen/Rappel pull request #230
Opened 2023-10-02 16:52 UTC by JamesKunstle

Uses our identified list of contributors within the wasm ecosystem, plus their pagerank centrality metrics, and begins to identify repos of high interest to those contributors.

2023-10-03 17:58 UTC, cdolfi commented
@JamesKunstle whats the relationship between the two notebooks if any?

2023-10-03 18:38 UTC, oindrillac commented on notebooks/project_discovery/project_discovery.ipynb
do you want to remove this from the PR as I think you are covering everything done here in a different way [notebooks/project_discovery/repo_discovery.ipynb](https://github.com/oss-aspen/Rappel/pull/230/files#diff-94b60b106a7e76d57654b622f302ee0c90ae07ca49566771a78fbc84fee39450)

2023-10-03 18:47 UTC, JamesKunstle commented on notebooks/project_discovery/project_discovery.ipynb
It's just there pending rebase, will remove later. Disregard for the time being.

2023-10-03 19:30 UTC, cdolfi commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>"kernal of projects"- Does this mean grouping of projects? </p><p> </p><p>Either way might be good to change the term to be something other than "kernel". Could see some confusion on if this is about projects involving the kernel</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/230/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2023-10-03 19:30 UTC, cdolfi commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>Would be good to reference which notebook this comes from</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/230/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='5'/>

2023-10-03 19:30 UTC, cdolfi commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>good to add that the github api only allows to go back 2 months now but with augur as time goes the data will only get more rich </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/230/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='7'/>

2023-10-03 19:30 UTC, cdolfi commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>is comment still relevant?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/230/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='10'/>

2023-10-03 19:30 UTC, cdolfi commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>insert image of graph</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/230/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='15'/>

2023-10-03 19:30 UTC, cdolfi commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>insert image</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/230/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='18'/>

2023-10-03 19:30 UTC, cdolfi commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>Is this difference in size that the 370K are the events from the identified contributors vs the 3.7 million are all of the events for the contributors on our augur repos? </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/230/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='22'/>

2023-10-03 19:31 UTC, cdolfi requested changes
This notebook looks great so far. Added some small comments and will rereview when the graph images are added

2023-10-03 19:33 UTC, cdolfi commented
Also I would say we should come up for some more descriptive names for "project_discovery" and "repo_discovery" as its hard to distinguish between the two

2023-10-06 16:13 UTC, JamesKunstle commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>added</p>

2023-10-06 16:15 UTC, JamesKunstle commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>added</p>

2023-10-06 16:15 UTC, JamesKunstle commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>lol no</p>

2023-10-06 16:15 UTC, JamesKunstle commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>++</p>

2023-10-06 16:16 UTC, JamesKunstle commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>++</p>

2023-10-06 16:18 UTC, JamesKunstle commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>Clarified.</p>

2023-10-06 16:21 UTC, JamesKunstle commented
> Also I would say we should come up for some more descriptive names for "project_discovery" and "repo_discovery" as its hard to distinguish between the two

Certainly agree, idk a better name off the top of my head but the current names are certainly not ideal

2023-10-06 16:21 UTC, JamesKunstle commented
@cdolfi made changes based on your comments.

2023-10-09 17:59 UTC, cdolfi commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>file image still not coming up. I would try a png as that format has shown to work before and this format also worked in another file: </p><p> </p><pre class="ql-syntax" spellcheck="false">Image(filename="wasm_histogram.png")
</pre><p> </p>

2023-10-09 18:02 UTC, JamesKunstle commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
oh I fixed that and forgot to push, lemme fix that in a bit before you continue.

2023-10-09 18:03 UTC, cdolfi requested changes
Rereviewed and resolved all of the comments that were addressed. Images are still not showing up for some reason. Added in some code from another notebook that showed said images

2023-10-09 19:53 UTC, JamesKunstle commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
yeah, generally I agree. for public consumption I'd change the name, but purely for mathematical formalism 'kernel' is a valid word for what I'm trying to describe.

I don't like the term 'core' because there's no guarantee that the projects that we initially consider ARE core to an ecosystem, they could be peripheral.

We could call them "observed" or something but that's a pretty loose approximation of what I want to say.

2023-10-09 19:54 UTC, JamesKunstle commented
Images should be fixed

2023-10-09 20:04 UTC, cdolfi commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
If you want to keep kernal I am fine with that. I would just put a bolded note at the top the kernal is not referring to the linux kernal or any type of proper noun or project type

2023-10-09 20:07 UTC, cdolfi commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>Can you update graph to not include the legend for the graph is more visible?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/230/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='20'/>

2023-10-09 20:07 UTC, cdolfi commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>Can you update graph to not include the legend for the graph is more visible? </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/230/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='31'/>

2023-10-09 20:08 UTC, cdolfi commented
#233 opened this issue for the naming conflict

2023-10-09 20:16 UTC, JamesKunstle commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
Note made

2023-10-09 20:16 UTC, JamesKunstle commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
updated

2023-10-09 20:16 UTC, JamesKunstle commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
updated

2023-10-09 20:25 UTC, cdolfi approved these changes
lgtm! once @hemajv and @oindrillac take a look ill be good to merge

2023-10-11 15:46 UTC, JamesKunstle commented
@cdolfi @oindrillac @hemajv cleaned up the branch, removed Oindrilla's notebook, streamlined merge.

2023-10-12 12:25 UTC, oindrillac commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #5.    fig_ec.update_layout(showlegend=False)
</pre><p>just a nit - should x and y axis lables be events and count?</p><p>and for the next plot too?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/230/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='15'/>

2023-10-12 12:25 UTC, oindrillac commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>I like this observation ++</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/230/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='32'/>

2023-10-12 12:25 UTC, oindrillac commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>Are the blue stacks general repos and red known? Can you add a short blurb on your interpretation of this plot? since the image is a little hard to read</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/230/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='40'/>

2023-10-12 12:27 UTC, oindrillac commented
Apologize for the late review. Thanks is great! Thanks @JamesKunstle 
Just added some minor comments. No major blockers from this getting merged.

2023-10-13 18:06 UTC, hemajv commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>++</p>

2023-10-13 18:08 UTC, hemajv commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>do we want to print out the whole list because it makes the rendered output quite large in the notebook, maybe we can just display the first 5 (for cleaner rendering of the notebook)?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/230/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='22'/>

2023-10-13 18:08 UTC, hemajv commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>Maybe I missed this, but I don't see 'risingwavelabs/risingwave' in the above plot?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/230/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='32'/>

2023-10-13 18:08 UTC, hemajv commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>maybe add "Hence, P-hat would be our unknown contributors."</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/230/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='34'/>

2023-10-13 18:08 UTC, hemajv commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>Can you also add a <code>Conclusion</code> section at the end of the notebook to highlight the main takeaways and summarize your findings? </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/230/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='40'/>

2023-10-13 18:09 UTC, hemajv commented
@JamesKunstle thanks for your work on this 👍  It looks great! 
I've added a few comments, ptal

2023-11-07 17:59 UTC, JamesKunstle commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>updated labels for all bar graphs</p>

2023-11-07 18:00 UTC, JamesKunstle commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>shortened to first 10</p>

2023-11-07 18:02 UTC, JamesKunstle commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>++</p>

2023-11-07 18:02 UTC, JamesKunstle commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>++</p>

2023-11-07 18:26 UTC, JamesKunstle commented
@hemajv @oindrillac addressed some comments

2023-11-08 18:46 UTC, hemajv approved these changes
Thanks for making the changes @JamesKunstle! Looks great 🎉 
/lgtm

2023-11-08 18:55 UTC, oindrillac commented on notebooks/project_discovery/repo_discovery.ipynb
> +{
<p>Thanks for adding this observation. Really like this</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/230/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='41'/>

2023-11-08 18:55 UTC, oindrillac approved these changes
LGTM! Thanks for the changes

2023-11-08 20:59 UTC, cdolfi commented
@JamesKunstle Any final changes you want to put in? If not going to merge!

2023-11-08 21:47 UTC, JamesKunstle commented
@cdolfi yeah all set! then I'll rebase and we can knock the other one out too

2023-11-08 21:54 UTC, merged