AI projects - repo discovery
oss-aspen/Rappel pull request #258
Opened 2024-08-16 23:42 UTC by Prudhvivuda

Iterating on the work done here for the AI repositories - https://github.com/oss-aspen/Rappel/tree/main/notebooks/project_discovery/repo_discovery

2024-08-29 17:00 UTC, cdolfi commented on notebooks/emerging_ai_projects/repo_discovery.ipynb
> +{
<p>(apply to graph below as well) slice the strings after ".com/repos/" and make the graph itself bigger </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/258/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='37'/>

2024-09-06 09:19 UTC, dominikkawka approved these changes

2024-09-09 23:27 UTC, hemajv requested changes
@Prudhvivuda nice work! I've left some comments, ptal

2024-09-10 06:11 UTC, JamesKunstle commented
I posted comments but ReviewNB didn't save them.

The core problem I have is that the Event Stream isn't representative of the population of GitHub (perhaps it really never was in the original work) so we can't draw conclusions about the results. I think the database that this work is using is based on a set of repos that are assumed to be AI facing, rather than a roughly random set of repos.

I don't have a solution for this without rebuilding the database, but I think mentioning this limitation is imperitive.

2024-09-17 10:09 UTC, cdolfi commented
<p>Change the Legend to say "Seed Repo" "Non seed Repo" instead of true/false</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/258/discussion/#comment-2339323629'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-09-17 20:31 UTC, Prudhvivuda commented
<p>done</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/258/discussion/#comment-2339323629'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-09-27 20:23 UTC, Prudhvivuda commented
<p>I think this shows the number of events from the general population and sub population (known contributors).</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/258/discussion/#comment-2379962858'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-09-27 20:26 UTC, cdolfi approved these changes
lgtm

2024-09-27 20:26 UTC, merged